import {
    CalendarCheckIcon,
    CalendarIcon,
    CheckIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    CircleAlertIcon,
    CircleCheckIcon,
    CircleInfoIcon,
    CircleQuestionIcon,
    ClockCheckIcon,
    ClockIcon,
    CopyCheckIcon,
    CopyIcon,
    DatabaseBackupIcon,
    DatabaseIcon,
    DatabaseSearchIcon,
    EllipsisIcon,
    EllipsisMenuIcon,
    Grid,
    H2,
    HardDriveDownloadIcon,
    HardDriveIcon,
    HardDriveUploadIcon,
    LaptopIcon,
    MenuIcon, MessageBrokerIcon,
    MonitorIcon,
    NetworkIcon,
    Panel,
    RouterIcon,
    SatelliteDishIcon, SatelliteIcon, ServerClockIcon,
    ServerCogIcon,
    ServerCrashIcon,
    ServerIcon,
    ServerOffIcon, ShareIcon,
    SmartphoneIcon,
    Text,
    Tooltip,
    TriangleAlertIcon,
    WifiIcon,
    XIcon
} from "@zoria-ui/react";

export function IconsDemo() {
    return <Panel>
        <Panel.Header><H2>Icons</H2></Panel.Header>
        <Panel.Body>
            <Grid cols={12}>
                <Tooltip>
                    <Tooltip.Trigger>
                        <XIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>XIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ChevronDownIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ChevronDownIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ChevronLeftIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ChevronLeftIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ChevronRightIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ChevronRightIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ChevronUpIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ChevronUpIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <CalendarIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>CalendarIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <CalendarCheckIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>CalendarCheckIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ClockIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ClockIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ClockCheckIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ClockCheckIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <CheckIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>CheckIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <CopyIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>CopyIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <CopyCheckIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>CopyCheckIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <MenuIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>MenuIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <EllipsisMenuIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>EllipsisMenuIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <EllipsisIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>EllipsisIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <DatabaseIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>DatabaseIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <DatabaseBackupIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>DatabaseBackupIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <DatabaseSearchIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>DatabaseSearchIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ServerIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ServerIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ServerCogIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ServerCogIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ServerCrashIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ServerCrashIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ServerOffIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ServerOffIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ServerClockIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ServerClockIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <HardDriveIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>HardDriveIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <HardDriveDownloadIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>HardDriveDownloadIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <HardDriveUploadIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>HardDriveUploadIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <MonitorIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>MonitorIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <LaptopIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>LaptopIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <SmartphoneIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>SmartphoneIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <WifiIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>WifiIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <RouterIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>RouterIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <SatelliteDishIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>SatelliteDishIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <SatelliteIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>SatelliteIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <NetworkIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>NetworkIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <MessageBrokerIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>MessageBrokerIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <TriangleAlertIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>TriangleAlertIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <CircleAlertIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>CircleAlertIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <CircleCheckIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>CircleCheckIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <CircleQuestionIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>CircleQuestionIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <CircleInfoIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>CircleInfoIcon</Text></Tooltip.Body>
                </Tooltip>
                <Tooltip>
                    <Tooltip.Trigger>
                        <ShareIcon/>
                    </Tooltip.Trigger>
                    <Tooltip.Body><Text>ShareIcon</Text></Tooltip.Body>
                </Tooltip>
            </Grid>
        </Panel.Body>
    </Panel>;
}